#!/usr/bin/env python3
"""The evidence bundle, assembled from artefacts rather than asserted.

Nothing here decides that a requirement passed.  Each check is handed two things
that the system produced independently and reports whether they agree: the batch
the ledger recorded against the batch the resumed loader rebuilt, the content hash
in a manifest against the hash recomputed from the token file on disk, the
throughput in the performance report against a count taken from the ledger.

Every entry names the file a reader can open to see the comparison for themselves,
and carries the values that were compared, so the bundle can be disproved.
"""
import json, os


class Evidence:
    def __init__(self, artifacts_dir):
        self.dir = artifacts_dir
        self.checks = []

    def add(self, requirement, ok, evidence_files, detail, values=None):
        entry = {
            "requirement": requirement,
            "result": "PASS" if ok else "FAIL",
            "evidence": [os.path.relpath(f, self.dir) if os.path.isabs(f) else f
                         for f in (evidence_files if isinstance(evidence_files, (list, tuple))
                                   else [evidence_files])],
            "detail": detail,
            "values": values or {},
        }
        self.checks.append(entry)
        return entry

    @property
    def all_passed(self):
        return all(c["result"] == "PASS" for c in self.checks)

    def write_json(self, path, extra=None):
        payload = {
            "schema": "era-v5-session6-evidence/1",
            "generated_by": "run_demo.py",
            "all_passed": self.all_passed,
            "n_checks": len(self.checks),
            "n_failed": sum(1 for c in self.checks if c["result"] == "FAIL"),
            "checks": self.checks,
        }
        if extra:
            payload.update(extra)
        with open(path, "w") as f:
            json.dump(payload, f, indent=1, ensure_ascii=False)
        return payload

    def write_md(self, path, run_summary):
        lines = [
            "# Session 6 evidence",
            "",
            "Generated by `run_demo.py`.  Every row is a comparison between two things",
            "the system produced independently.  The evidence column names the file that",
            "holds the values compared.",
            "",
            f"- Run id: `{run_summary.get('run_id')}`",
            f"- Model: {run_summary.get('parameters', 0):,} parameters, "
            f"vocabulary {run_summary.get('vocab_size', 0):,}, character level",
            f"- Tokenizer hash: `{str(run_summary.get('tokenizer_hash', ''))[:32]}`",
            f"- Steps trained: {run_summary.get('steps')}, "
            f"token positions consumed: {run_summary.get('token_positions', 0):,}",
            f"- Result: **{'all checks passed' if self.all_passed else 'FAILURES PRESENT'}** "
            f"({sum(1 for c in self.checks if c['result'] == 'PASS')} of {len(self.checks)})",
            "",
            "| Requirement | Result | Evidence | What was compared |",
            "| --- | --- | --- | --- |",
        ]
        for c in self.checks:
            ev = ", ".join(f"`{e}`" for e in c["evidence"])
            detail = c["detail"].replace("|", "\\|")
            lines.append(f"| {c['requirement']} | **{c['result']}** | {ev} | {detail} |")
        lines += ["", "## Values behind each row", ""]
        for c in self.checks:
            if not c["values"]:
                continue
            lines.append(f"### {c['requirement']}")
            lines.append("")
            lines.append("```json")
            lines.append(json.dumps(c["values"], indent=1, ensure_ascii=False)[:2600])
            lines.append("```")
            lines.append("")
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")
        return path
