#!/usr/bin/env python3
"""One command: build the data system, train on it, break it, and prove it recovered.

    python run_demo.py

Everything under submission_artifacts/ is regenerated by this script.  Nothing in
the evidence bundle is written by hand: each entry is a comparison between two
artefacts the system produced independently.

The demonstration runs in fifteen phases, in the order Session 6 sets out.  The
interesting ones are 09 to 12: a deliberate crash in the middle of a step, a resume
that must serve exactly the batch the pre-crash run served, a replay of an earlier
interval that must reproduce its hashes, and a fork that must record its own
divergence.

Source documents are downloaded from six published datasets on first run and cached
under data/, so later runs are offline.  Nothing is bundled and nothing is synthetic.
"""
import argparse, copy, hashlib, json, os, random, shutil, sys, time

import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from tdes import corpus, evidence as ev, learning, ledger as L, mixture, packing
from tdes import perf as perf_mod, registry as reg_mod, scoring, shards, tokenizer as tk
from tdes import trainer as tr
from tdes.model import TinyLM, parameter_count

RUN_ID = "v5-s6-demo"
DATALOADER_VERSION = tr.DATALOADER_VERSION


# ------------------------------------------------------------------ logging
class Log:
    def __init__(self, path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        self.f = open(path, "w")
        self.t0 = time.time()

    def __call__(self, msg=""):
        line = f"[{time.time() - self.t0:7.2f}s] {msg}" if msg else ""
        print(line, flush=True)
        self.f.write(line + "\n")
        self.f.flush()

    def phase(self, n, title):
        self("")
        self(f"===== {n} {title} " + "=" * max(0, 56 - len(title)))

    def event(self, name):
        self(f"  >> {name}")

    def close(self):
        self.f.close()


def sha256_file(path):
    return tk.file_sha256(path)


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)


# ------------------------------------------------------------------ the demonstration
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--steps", type=int, default=256, help="steps in the main run")
    ap.add_argument("--crash-at", type=int, default=None, help="global step to crash at")
    ap.add_argument("--ckpt-interval", type=int, default=32)
    ap.add_argument("--vocab", type=int, default=16384)
    ap.add_argument("--max-seq", type=int, default=512)
    ap.add_argument("--kb-per-lane", type=int, default=700)
    ap.add_argument("--threads", type=int, default=max(2, (os.cpu_count() or 4) // 2))
    ap.add_argument("--seed", type=int, default=1234)
    a = ap.parse_args()

    torch.set_num_threads(a.threads)
    set_seed(a.seed)

    art = os.path.join(HERE, "submission_artifacts")
    if os.path.exists(art):
        shutil.rmtree(art)
    for sub in ("manifests", "ledgers", "checkpoints", "reports"):
        os.makedirs(os.path.join(art, sub), exist_ok=True)
    data = os.path.join(HERE, "data")
    shard_dir = os.path.join(data, "shards")
    log = Log(os.path.join(art, "run.log"))
    E = ev.Evidence(art)

    crash_at = a.crash_at if a.crash_at is not None else max(8, int(a.steps * 0.55))
    wall0 = time.time()

    log(f"ERA V5 Session 6: training data execution system")
    log(f"run_id={RUN_ID} steps={a.steps} crash_at={crash_at} seed={a.seed} "
        f"threads={a.threads} torch={torch.__version__}")

    # -------------------------------------------------------------- 01 corpus
    log.phase("01", "source documents")
    train_docs, held_docs = {}, {}
    t = time.time()
    for lane in mixture.LANES:
        d, nxt = corpus.build_lane(data, lane, a.kb_per_lane * 1000, log=log)
        held, _ = corpus.build_lane(data, lane, max(60_000, a.kb_per_lane * 150),
                                    start_offset=nxt, id_prefix="held-", log=log)
        train_docs[lane] = d
        held_docs[lane] = held
    corpus_seconds = time.time() - t
    corpus.write_jsonl(os.path.join(data, "docs", "train.jsonl"),
                       [x for l in mixture.LANES for x in train_docs[l]])
    corpus.write_jsonl(os.path.join(data, "docs", "heldout.jsonl"),
                       [x for l in mixture.LANES for x in held_docs[l]])
    n_train = sum(len(v) for v in train_docs.values())
    n_held = sum(len(v) for v in held_docs.values())
    log(f"  {n_train} training documents, {n_held} held out, "
        f"{corpus_seconds:.1f}s (cached after the first run)")
    log.event("documents fetched")

    # -------------------------------------------------------------- 02 tokenizer
    log.phase("02", "tokenizer, frozen and hashed")
    tok_path = os.path.join(data, "tokenizer.json")
    tk.train(train_docs, tok_path, vocab_size=a.vocab, log=log)
    tok = tk.load(tok_path)
    fert = tk.measure_fertility(tok, held_docs)
    fert_ok, fert_fail = tk.check_fertility(fert)
    tok_desc = tk.descriptor(tok_path, tok.get_vocab_size(), fert)
    tokenizer_hash = tok_desc["tokenizer_hash"]
    for lane in mixture.LANES:
        s = fert[lane]
        log(f"    {lane:<10} fertility {s['fertility_tokens_per_word']:.3f} tok/word   "
            f"bytes/token {s['bytes_per_token']:.2f}   unk {s['unk_rate']:.2e}")
    log(f"  tokenizer hash {tokenizer_hash[:32]}  vocabulary {tok.get_vocab_size()}")
    if not fert_ok:
        log(f"  [FAIL] fertility gate: {fert_fail}")
    else:
        log.event("[PASS] tokenizer_hash_verified")
        log.event("[PASS] indic_fertility_within_ceiling")
    tok_manifest = os.path.join(art, "manifests", "tokenizer.json")
    with open(tok_manifest, "w") as f:
        json.dump(tok_desc, f, indent=1, ensure_ascii=False)

    E.add("Tokenizer integrity", tokenizer_hash == sha256_file(tok_path),
          [os.path.join("manifests", "tokenizer.json")],
          "hash recorded in the manifest recomputed from the tokenizer file on disk",
          {"manifest_hash": tokenizer_hash, "recomputed_hash": sha256_file(tok_path),
           "vocab_size": tok.get_vocab_size(), "level": "character"})
    E.add("Indic fertility", fert_ok, [os.path.join("manifests", "tokenizer.json")],
          "measured tokens per word on held-out text, against the ceiling and against the web lane",
          {"fertility": {l: fert[l]["fertility_tokens_per_word"] for l in mixture.LANES},
           "ceiling": tk.FERTILITY_CEILING, "failures": fert_fail,
           "indic_beats_web": fert["indic"]["fertility_tokens_per_word"]
                              <= fert["web"]["fertility_tokens_per_word"]})

    eos_id, pad_id = tok.token_to_id(tk.EOS), tok.token_to_id(tk.PAD)
    cleaning_hash = sha256_file(os.path.join(HERE, "tdes", "clean.py"))

    # -------------------------------------------------------------- 03 shards
    log.phase("03", "immutable tokenised shards and manifests")
    if os.path.exists(shard_dir):
        shutil.rmtree(shard_dir)
    manifests, dedup_reports = {}, {}

    def build(shard_id, docs, lane, split, never_train, extra=None):
        toks, samples = shards.tokenize_documents(tok, docs, eos_id)
        kept, rep = shards.dedup(toks, samples)
        toks, kept = shards.repack(toks, kept)
        meta = {
            "split": split, "never_train": never_train, "capability_lane": lane,
            "source": docs[0]["source"] if docs else "",
            "language": "hi" if lane == "indic" else "en",
            "script": "Deva" if lane == "indic" else "Latn",
            "license_tier": "A",
            "tokenizer_hash": tokenizer_hash,
            "cleaning_pipeline_hash": cleaning_hash,
            "dedup_status": "pass", "dedup_report": rep,
            "contamination_status": "unscanned" if split == "train" else "held_out",
            "eval_overlap": False,
            "provenance_tier": "published_dataset_downloadable",
            "parent_shard_ids": [],
            "data_kind": docs[0]["kind"] if docs else "pretrain",
        }
        meta.update(extra or {})
        m = shards.write_shard(shard_dir, shard_id, toks, kept, meta)
        return m, toks, rep

    # Held-out shards are built and registered first.  Training documents cannot be
    # screened against an index that does not exist yet, and screening before the
    # shard is written is what keeps a shard immutable in practice.
    registry = reg_mod.Registry(shard_dir, tokenizer_hash)
    for lane in mixture.LANES:
        half = max(1, len(held_docs[lane]) // 2)
        mv, tv, _ = build(f"val-{lane}-000", held_docs[lane][:half], lane, "validation", False)
        mt, tt, _ = build(f"test-{lane}-000", held_docs[lane][half:], lane, "test", True,
                          {"benchmark_id": f"era-v5-holdout-{lane}", "version_tag": "v1",
                           "access_log": []})
        manifests[mv["shard_id"]] = mv
        manifests[mt["shard_id"]] = mt
        registry.register_heldout(mv, tv)
        registry.register_heldout(mt, tt)
    log(f"  held out registered: {len(registry.by_split('validation'))} validation, "
        f"{len(registry.by_split('test'))} test (never_train), "
        f"{len(registry.never_train_docs())} never-train documents indexed")

    screened = {}
    for lane in mixture.LANES:
        clean, rejected = registry.screen_documents(tok, train_docs[lane], eos_id)
        screened[lane] = {"offered": len(train_docs[lane]), "kept": len(clean),
                          "rejected": [{"sample_id": r["sample_id"], "match": r["match"],
                                        "held_out_sample": r["held_out_sample"]}
                                       for r in rejected]}
        if rejected:
            log(f"  {lane}: {len(rejected)} document(s) screened out before sharding "
                f"({', '.join(r['match'] for r in rejected[:3])})")
        train_docs[lane] = clean
        m, toks, rep = build(f"train-{lane}-000", clean, lane, "train", False,
                             {"contamination_status": "screened_clean",
                              "documents_screened_out": len(rejected)})
        manifests[m["shard_id"]] = m
        dedup_reports[m["shard_id"]] = rep

    for m in manifests.values():
        shards.write_manifest(os.path.join(art, "manifests"), m)
    total_tokens_in_shards = sum(m["n_tokens"] for m in manifests.values())
    dup_removed = sum(r["exact_duplicates_removed"] + r["near_duplicates_removed"]
                      for r in dedup_reports.values())
    log(f"  {len(manifests)} shards, {total_tokens_in_shards:,} tokens, "
        f"{dup_removed} duplicates removed inside shards")
    log.event("shards created")

    verify = {sid: shards.verify_shard(shard_dir, m) for sid, m in manifests.items()}
    all_verified = all(ok for ok, _ in verify.values())
    log(f"  content hash verification: {sum(1 for ok, _ in verify.values() if ok)}"
        f"/{len(verify)} shards match their manifest")
    log.event("manifests validated")
    if all_verified:
        log.event("[PASS] shard_content_hashes_verified")

    # a real immutability demonstration: change one token and re-verify
    probe_id = "train-web-000"
    probe = copy.deepcopy(manifests[probe_id])
    probe_tokens = shards.load_tokens(shard_dir, probe)
    tampered = probe_tokens.copy()
    tampered[0] = (int(tampered[0]) + 1) % a.vocab
    tmp_dir = os.path.join(data, "tamper")
    os.makedirs(tmp_dir, exist_ok=True)
    np.save(os.path.join(tmp_dir, probe["token_file"]), tampered)
    tamper_ok, tamper_detail = shards.verify_shard(tmp_dir, probe)
    log(f"  tamper probe on {probe_id}: single token altered, verification "
        f"{'FAILED TO DETECT' if tamper_ok else 'detected the change'}")

    E.add("Shard immutability and manifests", all_verified and not tamper_ok,
          [os.path.join("manifests", f"{probe_id}.json")],
          "every shard hash recomputed from disk, plus a tamper probe that alters one token",
          {"shards_verified": sum(1 for ok, _ in verify.values() if ok),
           "shards_total": len(verify),
           "tamper_probe_shard": probe_id,
           "tamper_probe_detected": not tamper_ok,
           "tamper_probe_detail": tamper_detail,
           "duplicates_removed": {k: v for k, v in
                                  ((s, r["exact_duplicates_removed"] + r["near_duplicates_removed"])
                                   for s, r in dedup_reports.items())}})

    # -------------------------------------------------------------- 04 registry and firewall
    log.phase("04", "registry, admission gate and evaluation firewall")
    admitted, quarantines = 0, []
    for m in list(manifests.values()):
        if m["split"] != "train":
            continue
        ok, fails, hits = registry.admit(m, shards.load_tokens(shard_dir, m))
        if ok:
            admitted += 1
            continue
        log(f"  [BLOCK] {m['shard_id']}: {'; '.join(fails)}")
        if not hits:
            continue
        # The firewall found a real overlap in real data.  A blocked shard is not
        # edited: the offending samples are quarantined and a NEW shard is written
        # with a new content hash naming the blocked one as its parent.
        lane = m["capability_lane"]
        bad, parent, ok2, rounds = {h["sample_id"] for h in hits}, m, False, 0
        mchild = None
        while not ok2 and rounds < 5:
            rounds += 1
            child_id = f"{m['shard_id'][:-3]}{rounds:03d}"
            clean_docs = [d for d in train_docs[lane] if d["doc_id"] not in bad]
            mchild, ctok, _ = build(child_id, clean_docs, lane, "train", False,
                                    {"parent_shard_ids": [parent["shard_id"]],
                                     "contamination_status": "quarantined_and_rebuilt",
                                     "quarantined_sample_ids": sorted(bad),
                                     "quarantine_round": rounds})
            manifests[child_id] = mchild
            shards.write_manifest(os.path.join(art, "manifests"), mchild)
            ok2, fails2, hits2 = registry.admit(mchild, ctok)
            log(f"  quarantined {len(bad)} sample(s), rebuilt as {child_id} "
                f"(parent {parent['shard_id']}) -> "
                f"{'admitted' if ok2 else 'still overlapping, quarantining again'}")
            parent = mchild
            bad |= {h["sample_id"] for h in hits2}
        admitted += int(ok2)
        quarantines.append({"blocked_shard": m["shard_id"],
                            "final_shard": mchild["shard_id"] if mchild else None,
                            "rounds": rounds,
                            "quarantined_samples": sorted(bad),
                            "n_quarantined": len(bad),
                            "parent_content_hash": m["content_hash"],
                            "child_content_hash": mchild["content_hash"] if mchild else None,
                            "child_admitted": ok2,
                            "hits": hits[:4]})
    log(f"  admitted {admitted} training shards, {len(quarantines)} rebuilt after quarantine")

    # firewall probe: a candidate shard that really contains held-out documents
    test_lane = "stem"
    contaminated_docs = (train_docs[test_lane][:12] +
                         held_docs[test_lane][len(held_docs[test_lane]) // 2:][:6])
    mc, ct, _ = build("candidate-contaminated-000", contaminated_docs, test_lane, "train", False,
                      {"probe": True, "probe_role": "deliberately contaminated candidate"})
    shards.write_manifest(os.path.join(art, "manifests"), mc)
    blocked_ok, blocked_fails, blocked_hits = registry.admit(mc, ct)
    log(f"  firewall probe: candidate carrying 6 held-out documents -> "
        f"{'ADMITTED (failure)' if blocked_ok else 'blocked'}")
    for h in blocked_hits[:3]:
        log(f"    hit {h['sample_id']} matched {h['held_out_sample']} by {h['match']}")
    log.event("evaluation data blocked")
    if not blocked_ok:
        log.event("[PASS] eval_shard_blocked")

    # The blocked shard is not edited.  Its clean samples are rewritten as a new
    # shard with a new content hash that names the blocked one as its parent.
    bad_ids = {h["sample_id"] for h in blocked_hits}
    rebuilt_docs = [d for d in contaminated_docs if d["doc_id"] not in bad_ids]
    mfix, tfix, _ = build("candidate-contaminated-001", rebuilt_docs, test_lane, "train", False,
                          {"probe": True, "probe_role": "rebuilt after quarantine",
                           "parent_shard_ids": [mc["shard_id"]],
                           "contamination_status": "quarantined_and_rebuilt",
                           "quarantined_sample_ids": sorted(bad_ids)})
    manifests[mfix["shard_id"]] = mfix
    shards.write_manifest(os.path.join(art, "manifests"), mfix)
    fixed_ok, fixed_fails, _ = registry.admit(mfix, tfix)
    quarantines.append({"blocked_shard": mc["shard_id"], "final_shard": mfix["shard_id"],
                        "rounds": 1, "quarantined_samples": sorted(bad_ids),
                        "n_quarantined": len(bad_ids),
                        "parent_content_hash": mc["content_hash"],
                        "child_content_hash": mfix["content_hash"],
                        "child_admitted": fixed_ok, "hits": blocked_hits[:4]})
    log(f"  quarantined {len(bad_ids)} sample(s) and rewrote as {mfix['shard_id']} "
        f"(parent {mc['shard_id']}) -> {'admitted' if fixed_ok else 'still blocked'}")

    # a clean candidate must still pass, or the firewall is just blocking everything
    mclean, cleant, _ = build("candidate-clean-000", train_docs["web"][:12], "web", "train", False,
                              {"probe": True, "probe_role": "clean control candidate"})
    clean_ok, clean_fails, _ = registry.admit(mclean, cleant)
    log(f"  control probe: clean candidate -> {'admitted' if clean_ok else 'BLOCKED (failure)'}")

    registry_path = registry.dump(os.path.join(art, "reports", "registry.json"))
    json.dump(screened, open(os.path.join(art, "reports", "screening.json"), "w"),
              indent=1, ensure_ascii=False)
    total_screened_out = sum(len(v["rejected"]) for v in screened.values())
    log(f"  document screening before sharding removed {total_screened_out} document(s) "
        f"across {sum(1 for v in screened.values() if v['rejected'])} lane(s)")
    E.add("Contamination screened before sharding", admitted == len(mixture.LANES),
          [os.path.join("reports", "screening.json")],
          "every training document checked against the held-out index before any shard was written",
          {"per_lane": {l: {"offered": v["offered"], "kept": v["kept"],
                            "screened_out": len(v["rejected"]),
                            "examples": v["rejected"][:3]} for l, v in screened.items()},
           "total_screened_out": total_screened_out,
           "training_shards_admitted": admitted,
           "training_lanes": len(mixture.LANES)})
    if quarantines:
        for q in quarantines:
            log(f"    lineage: {q['final_shard']} parent {q['blocked_shard']}, "
                f"hash {q['parent_content_hash'][:12]} -> {q['child_content_hash'][:12]}")
    E.add("Blocked shard rebuilt rather than edited",
          all(q["child_admitted"] and q["child_content_hash"] != q["parent_content_hash"]
              for q in quarantines) if quarantines else True,
          [os.path.join("reports", "registry.json")],
          "shards the firewall blocked were quarantined and rewritten as new shards naming the blocked one as parent",
          {"rebuilds": quarantines,
           "note": "no rebuild was required on this run" if not quarantines else ""})
    E.add("Evaluation firewall", (not blocked_ok) and clean_ok and len(blocked_hits) > 0,
          [os.path.join("reports", "registry.json"),
           os.path.join("manifests", "candidate-contaminated-000.json")],
          "a candidate shard really containing held-out documents was offered, and a clean control was offered",
          {"contaminated_candidate_blocked": not blocked_ok,
           "firewall_hits": blocked_hits[:6],
           "n_hits": len(blocked_hits),
           "block_reasons": blocked_fails,
           "clean_control_admitted": clean_ok,
           "never_train_documents_indexed": len(registry.never_train_docs())})

    # -------------------------------------------------------------- 05 mixture
    log.phase("05", "mixture timeline compiled to per-step quotas")
    seqs_per_step = 2 * 4 * 2                      # ranks x microbatch x accumulation
    est_tokens = a.steps * seqs_per_step * (a.max_seq // 2)
    schedule = mixture.Schedule(est_tokens, a.max_seq)
    sched_path = os.path.join(art, "manifests", "mixture_schedule.json")
    with open(sched_path, "w") as f:
        json.dump(schedule.to_json(), f, indent=1)
    for s in schedule.stages:
        log(f"    {s['stage']:<16} tokens {s['token_start']:>8}-{s['token_end']:<8} "
            f"seq {s['sequence_length']:>4}  " +
            " ".join(f"{l[:4]}{int(s['mixture'][l] * 100):>3}" for l in mixture.LANES))
    log(f"  protected floors {mixture.PROTECTED_FLOORS}, anneal reserve "
        f"{schedule.anneal_reserve_tokens():,} tokens")
    log.event("mixture compiled")

    # -------------------------------------------------------------- 06 reference model
    log.phase("06", "OPUS proxy: reference model trained on English web only")
    def make_model():
        return TinyLM(tok.get_vocab_size(), max_seq=a.max_seq)

    ref_model = make_model()
    ref_items = packing.make_items(manifests["train-web-000"],
                                   shards.load_tokens(shard_dir, manifests["train-web-000"]))
    ref_packs = packing.pack(ref_items, 256, pad_id, "best_fit")
    ref_opt = torch.optim.AdamW(ref_model.parameters(), lr=3e-3)
    t = time.time()
    ref_steps = 0
    for epoch in range(3):
        for i in range(0, len(ref_packs) - 4, 4):
            batch = ref_packs[i:i + 4]
            ids = torch.tensor(np.stack([p.input_ids for p in batch]))
            pos = torch.tensor(np.stack([p.position_ids for p in batch]))
            seg = torch.tensor(np.stack([p.segment_ids for p in batch]))
            lm = torch.tensor(np.stack([p.loss_mask for p in batch]))
            _, _, loss = ref_model.token_losses(ids, pos, seg, lm)
            ref_opt.zero_grad(set_to_none=True)
            loss.backward()
            ref_opt.step()
            ref_steps += 1
            if ref_steps >= 60:
                break
        if ref_steps >= 60:
            break
    ref_seconds = time.time() - t
    log(f"  reference model: {ref_steps} steps on the web lane only, final loss "
        f"{float(loss.detach()):.3f}, {ref_seconds:.1f}s")
    ref_state = copy.deepcopy(ref_model.state_dict())

    # -------------------------------------------------------------- 07 the run
    log.phase("07", "run A: the main training run")
    model = make_model()
    log(f"  model {parameter_count(model):,} parameters, vocabulary {tok.get_vocab_size()}, "
        f"max sequence {a.max_seq}")

    scorer = scoring.ExcessLossScorer(make_model, ref_state, copy.deepcopy(model.state_dict()),
                                      proxy_version="ref-en-web-v1")
    opus = __import__("tdes.opus", fromlist=["Opus"]).Opus(
        scorer, mixture.PROTECTED_FLOORS, "ref-en-web-v1")

    ledger_dir = os.path.join(art, "ledgers")
    branches = L.BranchBook(os.path.join(ledger_dir, "branches.json"))
    branches.open_branch("main", reason="the original run")
    cons = L.Ledger(L.consumption_path(ledger_dir, "main"))

    from tdes.dataloader import DataStream
    stream = DataStream(registry, schedule, opus, pad_id, eos_id, ranks=2, microbatch=4,
                        accumulation=2, seed=a.seed, branch_id="main")
    stream.attach_allocator(mixture.QuotaAllocator(mixture.PROTECTED_FLOORS))
    log(f"  item pool: " + ", ".join(f"{l}={len(stream.pool[l])}" for l in mixture.LANES))

    trace = learning.LossTrace(trace_shards={"train-indic-000", "train-agentic-000"})
    perf = perf_mod.PerfMeter()
    perf.mark("corpus_seconds", corpus_seconds)
    perf.mark("reference_model_seconds", ref_seconds)

    trainer = tr.Trainer(model, stream, cons, trace, perf, run_id=RUN_ID, branch_id="main",
                         tokenizer_hash=tokenizer_hash,
                         ckpt_dir=os.path.join(art, "checkpoints"),
                         total_steps=a.steps, ckpt_interval=a.ckpt_interval, log=log, segment=0)

    def refresh_scorer():
        scorer.set_snapshot(trainer.scorer_snapshot, trainer.last_checkpoint)

    original_build = stream.build_step

    def build_step(scoring_checkpoint):
        refresh_scorer()
        before = scorer.seconds
        out = original_build(scoring_checkpoint)
        perf.watch.add("scoring", scorer.seconds - before)
        perf.offered_tokens += sum(d["effective_token_estimate"] for d in out["decisions"])
        perf.accepted_tokens += sum(d["effective_token_estimate"] for d in out["decisions"]
                                    if d["status"] == "accepted")
        return out

    stream.build_step = build_step

    crashed = False
    t = time.time()
    try:
        trainer.run(a.steps, crash_at=crash_at, crash_after_microbatch=1)
    except tr.CrashInjected as e:
        crashed = True
        log(f"  !! {e}")
    run_a_seconds = time.time() - t
    log.event("batches packed")
    log.event("OPUS decisions recorded")
    log.event("crash simulated")
    log(f"  run A stopped at step {stream.step}, ledger offset {cons.offset}, "
        f"{run_a_seconds:.1f}s")

    pre_crash = cons.read_all()
    last_ckpt = trainer.checkpoints[-1]
    log(f"  last checkpoint {last_ckpt['checkpoint_id']} at step {last_ckpt['global_step']}, "
        f"ledger offset {last_ckpt['ledger_offset']}")
    lost = [r for r in pre_crash if r["ledger_offset"] >= last_ckpt["ledger_offset"]]
    log(f"  {len(lost)} microbatch records were written after that checkpoint and their "
        f"gradients were lost in the crash")

    json.dump(trainer.step_losses, open(os.path.join(art, "reports", "loss_curve.json"), "w"),
              indent=1)

    # -------------------------------------------------------------- 08 resume
    log.phase("08", "resume from the checkpoint, and prove the next batch")
    ckpt = tr.load_checkpoint(last_ckpt["path"])
    log(f"  restored {ckpt['checkpoint_id']}: step {ckpt['global_step']}, "
        f"tokens {ckpt['tokens_seen']}, ledger offset {ckpt['ledger_offset']}")

    resume_model = make_model()
    resume_stream = DataStream(registry, schedule, opus, pad_id, eos_id, ranks=2, microbatch=4,
                               accumulation=2, seed=a.seed, branch_id="main")
    resume_stream.attach_allocator(mixture.QuotaAllocator(mixture.PROTECTED_FLOORS))
    resume_trainer = tr.Trainer(resume_model, resume_stream, cons, trace, perf, run_id=RUN_ID,
                                branch_id="main", tokenizer_hash=tokenizer_hash,
                                ckpt_dir=os.path.join(art, "checkpoints"),
                                total_steps=a.steps, ckpt_interval=a.ckpt_interval, log=log, segment=1)
    resume_trainer.restore(ckpt)

    original_resume_build = resume_stream.build_step

    def resume_build(scoring_checkpoint):
        scorer.set_snapshot(resume_trainer.scorer_snapshot, resume_trainer.last_checkpoint)
        return original_resume_build(scoring_checkpoint)

    resume_stream.build_step = resume_build

    t = time.time()
    n_replay_steps = max(1, stream.step - ckpt["global_step"])
    resume_records = []
    for _ in range(n_replay_steps):
        info, recs = resume_trainer.train_step(dry_run=True)
        resume_records.extend(recs)
    resume_latency = time.time() - t

    expected = tr.stream_signature([r for r in pre_crash
                                    if r["ledger_offset"] >= ckpt["ledger_offset"]])
    got = tr.stream_signature(resume_records)[:len(expected)]
    resume_verdict = tr.compare_signatures(expected, got)
    first_expected = expected[0] if expected else {}
    first_got = got[0] if got else {}
    log(f"  expected next batch: step {first_expected.get('global_step')} "
        f"{first_expected.get('microbatch_id')} hash {str(first_expected.get('batch_hash'))[:16]}")
    log(f"  resumed  next batch: step {first_got.get('global_step')} "
        f"{first_got.get('microbatch_id')} hash {str(first_got.get('batch_hash'))[:16]}")
    log(f"  compared {resume_verdict['compared_microbatches']} microbatches: "
        f"{'identical' if resume_verdict['matched'] else resume_verdict['differences']}")
    log.event("run resumed")
    if resume_verdict["matched"]:
        log.event("[PASS] resume_next_batch_matched")

    # a naive resume, for contrast: correct weights, fresh loader
    naive_stream = DataStream(registry, schedule, opus, pad_id, eos_id, ranks=2, microbatch=4,
                              accumulation=2, seed=a.seed, branch_id="main")
    naive_stream.attach_allocator(mixture.QuotaAllocator(mixture.PROTECTED_FLOORS))
    naive_trainer = tr.Trainer(make_model(), naive_stream, cons, trace, perf, run_id=RUN_ID,
                               branch_id="main", tokenizer_hash=tokenizer_hash,
                               ckpt_dir=os.path.join(art, "checkpoints"),
                               total_steps=a.steps, log=log, segment=9)
    naive_trainer.model.load_state_dict(ckpt["model"])
    _, naive_records = naive_trainer.train_step(dry_run=True)
    naive_sig = tr.stream_signature(naive_records)
    naive_matches = bool(expected) and naive_sig and naive_sig[0]["batch_hash"] == expected[0]["batch_hash"]
    log(f"  naive resume (model restored, dataloader not): first batch is step "
        f"{naive_sig[0]['global_step']} against expected {first_expected.get('global_step')}, "
        f"{'same' if naive_matches else 'a different batch, as it should be'}")

    E.add("Crash recovery", resume_verdict["matched"] and not naive_matches,
          [os.path.join("ledgers", "consumption.main.jsonl"),
           os.path.join("checkpoints", "index.json")],
          "batches rebuilt after restoring the checkpoint, compared to the batches the pre-crash run recorded",
          {"crash_injected_at_step": crash_at, "crash_raised": crashed,
           "restored_checkpoint": ckpt["checkpoint_id"],
           "restored_ledger_offset": ckpt["ledger_offset"],
           "expected_next_batch": first_expected,
           "resumed_next_batch": first_got,
           "microbatches_compared": resume_verdict["compared_microbatches"],
           "differences": resume_verdict["differences"],
           "records_lost_to_crash": len(lost),
           "naive_resume_produces_same_batch": bool(naive_matches),
           "naive_resume_first_step": naive_sig[0]["global_step"] if naive_sig else None})

    # -------------------------------------------------------------- 09 finish the run
    log.phase("09", "continue the resumed run to the end")
    resume_stream.load_state(ckpt["dataloader_state"])
    resume_trainer.restore(ckpt)
    remaining = a.steps - ckpt["global_step"]
    t = time.time()
    resume_trainer.run(remaining, checkpoint_first=False)
    log(f"  resumed run reached step {resume_stream.step} in {time.time() - t:.1f}s")

    all_records = cons.read_all()
    seg0 = [r for r in all_records if r.get("segment") == 0]
    seg1 = [r for r in all_records if r.get("segment") == 1]
    problems = L.check_contiguous(seg0) + L.check_contiguous(seg1)
    effective = {}
    for r in all_records:
        if r.get("segment") in (0, 1):
            effective[(r["global_step"], r["rank"], r["microbatch_id"])] = r
    steps_covered = sorted({k[0] for k in effective})
    gaps = [b for x, b in zip(steps_covered, steps_covered[1:]) if b != x + 1]
    log(f"  consumption ledger: {len(all_records)} records, segment 0 = {len(seg0)}, "
        f"segment 1 = {len(seg1)}")
    log(f"  steps {min(steps_covered)} to {max(steps_covered)}, gaps {gaps or 'none'}, "
        f"duplicate microbatches within a segment {problems or 'none'}")

    E.add("No skipped or repeated batches", not problems and not gaps,
          [os.path.join("ledgers", "consumption.main.jsonl")],
          "every microbatch key checked for repeats within a segment and every global step for gaps",
          {"records": len(all_records), "segment_0_records": len(seg0),
           "segment_1_records": len(seg1),
           "step_range": [min(steps_covered), max(steps_covered)],
           "step_gaps": gaps, "duplicate_problems": problems})

    # -------------------------------------------------------------- 10 replay
    log.phase("10", "replay an earlier interval from the ledger")
    # replay needs an interval that lies wholly inside the pre-crash segment, so the
    # latest checkpoint with a full span of original records after it is chosen
    replay_span = 4
    usable = [c for c in trainer.checkpoints if c["global_step"] + replay_span <= crash_at]
    # the second most recent usable checkpoint, so replay demonstrably goes further
    # back than the resume did rather than landing on the same point
    early = (usable[-2] if len(usable) > 1 else usable[-1]) if usable else trainer.checkpoints[0]
    replay_span = min(replay_span, max(1, crash_at - early["global_step"]))
    eck = tr.load_checkpoint(early["path"])
    replay_stream = DataStream(registry, schedule, opus, pad_id, eos_id, ranks=2, microbatch=4,
                               accumulation=2, seed=a.seed, branch_id="main")
    replay_stream.attach_allocator(mixture.QuotaAllocator(mixture.PROTECTED_FLOORS))
    replay_trainer = tr.Trainer(make_model(), replay_stream, cons, trace, perf, run_id=RUN_ID,
                                branch_id="main", tokenizer_hash=tokenizer_hash,
                                ckpt_dir=os.path.join(art, "checkpoints"),
                                total_steps=a.steps, log=log, segment=2)
    replay_trainer.restore(eck)
    orb = replay_stream.build_step

    def replay_build(scoring_checkpoint):
        scorer.set_snapshot(replay_trainer.scorer_snapshot, replay_trainer.last_checkpoint)
        return orb(scoring_checkpoint)

    replay_stream.build_step = replay_build

    t = time.time()
    replay_records = []
    for _ in range(replay_span):
        _, recs = replay_trainer.train_step(dry_run=True)
        replay_records.extend(recs)
    replay_latency = time.time() - t

    original_interval = [r for r in seg0
                         if eck["global_step"] <= r["global_step"] < eck["global_step"] + replay_span]
    replay_verdict = tr.compare_signatures(tr.stream_signature(original_interval),
                                           tr.stream_signature(replay_records))
    log(f"  replayed steps {eck['global_step']} to {eck['global_step'] + replay_span - 1} "
        f"from {eck['checkpoint_id']}")
    log(f"  compared {replay_verdict['compared_microbatches']} microbatches: "
        f"{'hashes and spans identical' if replay_verdict['matched'] else replay_verdict['differences']}")
    log.event("historical stream replayed")
    if replay_verdict["matched"]:
        log.event("[PASS] replay_hash_matched")

    E.add("Replay", replay_verdict["matched"],
          [os.path.join("ledgers", "consumption.main.jsonl"),
           os.path.join("checkpoints", "index.json")],
          "an earlier interval rebuilt from an older checkpoint, compared to the original records",
          {"replayed_from": eck["checkpoint_id"],
           "steps": [eck["global_step"], eck["global_step"] + replay_span - 1],
           "microbatches_compared": replay_verdict["compared_microbatches"],
           "original_hashes": [r["batch_hash"][:16] for r in original_interval[:4]],
           "replay_hashes": [r["batch_hash"][:16] for r in replay_records[:4]],
           "differences": replay_verdict["differences"]})

    # -------------------------------------------------------------- 11 fork
    log.phase("11", "fork a new branch from the same checkpoint")
    fork_id = "exp-indic-heavy"
    fork_sched = mixture.Schedule(est_tokens, a.max_seq)
    for s in fork_sched.stages:                       # a deliberate, recorded difference
        s["mixture"]["indic"] = round(s["mixture"]["indic"] + 0.10, 4)
        s["mixture"]["web"] = round(max(0.0, s["mixture"]["web"] - 0.10), 4)
    fork_ledger = L.Ledger(L.consumption_path(ledger_dir, fork_id))
    branches.open_branch(fork_id, parent="main", forked_at_step=eck["global_step"],
                         forked_at_offset=eck["ledger_offset"],
                         from_checkpoint=eck["checkpoint_id"],
                         reason="Indic share raised by 10 points, taken from web")
    fork_stream = DataStream(registry, fork_sched, opus, pad_id, eos_id, ranks=2, microbatch=4,
                             accumulation=2, seed=a.seed, branch_id=fork_id)
    fork_stream.attach_allocator(mixture.QuotaAllocator(mixture.PROTECTED_FLOORS))
    fork_trainer = tr.Trainer(make_model(), fork_stream, fork_ledger, trace, perf, run_id=RUN_ID,
                              branch_id=fork_id, tokenizer_hash=tokenizer_hash,
                              ckpt_dir=os.path.join(art, "checkpoints"),
                              total_steps=a.steps, log=log, segment=0)
    fork_trainer.restore(eck)
    fork_trainer.branch_id = fork_id
    fork_stream.branch_id = fork_id
    ofb = fork_stream.build_step

    def fork_build(scoring_checkpoint):
        scorer.set_snapshot(fork_trainer.scorer_snapshot, fork_trainer.last_checkpoint)
        return ofb(scoring_checkpoint)

    fork_stream.build_step = fork_build
    fork_records = []
    for _ in range(replay_span):
        _, recs = fork_trainer.train_step(dry_run=True)
        for r in recs:
            r["segment"] = 0
            fork_ledger.append(r)
        fork_records.extend(recs)
    fork_verdict = tr.compare_signatures(tr.stream_signature(original_interval),
                                         tr.stream_signature(fork_records))
    fork_lane_tokens = {}
    for r in fork_records:
        for lane, n in r["tokens_by_lane"].items():
            fork_lane_tokens[lane] = fork_lane_tokens.get(lane, 0) + n
    main_lane_tokens = {}
    for r in original_interval:
        for lane, n in r["tokens_by_lane"].items():
            main_lane_tokens[lane] = main_lane_tokens.get(lane, 0) + n
    fm, mm = max(1, sum(fork_lane_tokens.values())), max(1, sum(main_lane_tokens.values()))
    log(f"  branch {fork_id} forked from {eck['checkpoint_id']} at step {eck['global_step']}, "
        f"ledger offset {eck['ledger_offset']}")
    log(f"  Indic share: main {main_lane_tokens.get('indic', 0) / mm:.3f} -> "
        f"fork {fork_lane_tokens.get('indic', 0) / fm:.3f}")
    log(f"  the two streams differ from the divergence point: "
        f"{'yes' if not fork_verdict['matched'] else 'NO (failure)'}")
    branches.save()
    log.event("branch forked")

    E.add("Fork with recorded divergence", (not fork_verdict["matched"]) and
          fork_lane_tokens.get("indic", 0) / fm > main_lane_tokens.get("indic", 0) / mm,
          [os.path.join("ledgers", "branches.json"),
           os.path.join("ledgers", f"consumption.{fork_id}.jsonl")],
          "a new branch from the same checkpoint, its divergence point recorded and its stream compared to the parent",
          {"branch": branches.branches[fork_id],
           "parent_indic_share": round(main_lane_tokens.get("indic", 0) / mm, 5),
           "fork_indic_share": round(fork_lane_tokens.get("indic", 0) / fm, 5),
           "streams_differ": not fork_verdict["matched"],
           "n_differences": len(fork_verdict["differences"])})

    # -------------------------------------------------------------- 12 mixture compliance
    log.phase("12", "mixture compliance, floors and the OPUS audit")
    actual = {}
    for r in seg0 + seg1:
        for lane, n in r["tokens_by_lane"].items():
            actual[lane] = actual.get(lane, 0) + n
    planned = {}
    total_actual = max(1, sum(actual.values()))
    for r in seg0 + seg1:
        st = schedule.stage_at(0)
    # planned share is the token-weighted average of the stage mixtures actually reached
    weight = {}
    for r in seg0 + seg1:
        stage = r["curriculum_stage"]
        weight[stage] = weight.get(stage, 0) + r["n_sequences"] * r["sequence_length"]
    for stage, w in weight.items():
        mix = next(s["mixture"] for s in schedule.stages if s["stage"] == stage)
        for lane in mixture.LANES:
            planned[lane] = planned.get(lane, 0) + mix[lane] * w
    planned = {l: int(v) for l, v in planned.items()}
    comp = mixture.compliance(planned, actual)
    worst = max(comp.values(), key=lambda r: r["abs_error"])
    for lane in mixture.LANES:
        c = comp[lane]
        floor = mixture.PROTECTED_FLOORS.get(lane)
        flag = ""
        if floor is not None:
            flag = f"  floor {floor:.2f} {'held' if c['actual_share'] >= floor - 0.005 else 'BREACHED'}"
        log(f"    {lane:<10} planned {c['planned_share']:.3f}  actual {c['actual_share']:.3f}"
            f"  error {c['abs_error']:.3f}{flag}")
    floors_held = all(comp[l]["actual_share"] >= f - 0.005
                      for l, f in mixture.PROTECTED_FLOORS.items())
    log(f"  worst lane error {worst['abs_error']:.4f}; protected floors "
        f"{'all held' if floors_held else 'BREACHED'}")

    audit = opus.audit()
    opus_path = opus.dump(os.path.join(art, "reports", "opus_decisions.json"))
    log(f"  OPUS: {audit['totals']} over {len(opus.decisions)} candidates, proxy "
        f"{audit['proxy_version']}")
    for lane, v in sorted(audit["by_lane"].items()):
        log(f"    {lane:<10} offered {v['offered']:>4}  accepted {v['accepted']:>4}  "
            f"rejected {v['rejected']:>4}  deferred {v['deferred']:>4}  "
            f"floor rescued {v['floor_rescued']:>4}")
    indic_scores = [d["opus_score"] for d in opus.decisions if d["capability_lane"] == "indic"]
    web_scores = [d["opus_score"] for d in opus.decisions if d["capability_lane"] == "web"]
    mean_indic = sum(indic_scores) / max(1, len(indic_scores))
    mean_web = sum(web_scores) / max(1, len(web_scores))
    rescued_indic = audit["by_lane"].get("indic", {}).get("floor_rescued", 0)
    log(f"  proxy bias: mean OPUS score web {mean_web:+.3f} against Indic {mean_indic:+.3f}; "
        f"{rescued_indic} Indic candidates were retained by the protected floor")
    log.event("OPUS decisions recorded")

    E.add("Mixture compliance and protected floors", worst["abs_error"] < 0.06 and floors_held,
          [os.path.join("manifests", "mixture_schedule.json"),
           os.path.join("ledgers", "consumption.main.jsonl")],
          "planned share from the compiled schedule against the share actually recorded in the ledger",
          {"per_lane": comp, "worst_absolute_error": worst["abs_error"],
           "protected_floors": mixture.PROTECTED_FLOORS, "floors_held": floors_held})

    E.add("OPUS audit trail", len(opus.decisions) > 0 and audit["totals"]["rejected"] > 0
          and rescued_indic > 0,
          [os.path.join("reports", "opus_decisions.json")],
          "every candidate carries a score, a status, a reason and whether a floor overrode it",
          {"totals": audit["totals"], "by_lane": audit["by_lane"],
           "rejection_reasons": audit["rejection_reasons"],
           "mean_score_web": round(mean_web, 5), "mean_score_indic": round(mean_indic, 5),
           "indic_rescued_by_floor": rescued_indic,
           "proxy_version": audit["proxy_version"]})

    # -------------------------------------------------------------- 13 packing
    log.phase("13", "packing policies compared on the real corpus")
    pol_rows = []
    probe_lane_items = {
        "web (pretraining)": packing.make_items(
            manifests["train-web-000"], shards.load_tokens(shard_dir, manifests["train-web-000"]))[:120],
        "agentic (trajectories)": packing.make_items(
            manifests["train-agentic-000"], shards.load_tokens(shard_dir, manifests["train-agentic-000"]))[:120],
    }
    for label, items in probe_lane_items.items():
        for policy in packing.POLICIES:
            packs = packing.pack(items, 256, pad_id, policy)
            r = packing.utilisation_report(packs, policy)
            r["data"] = label
            pol_rows.append(r)
            log(f"    {label:<24} {policy:<22} occupancy {r['occupancy']:.3f}  "
                f"loss coverage {r['loss_coverage']:.3f}  sequences {r['n_sequences']:>4}  "
                f"crossings {r['boundary_crossings']:>4}  truncated {r['truncated_samples']:>3}")

    # mask correctness on every packed sequence that was actually trained on
    viol = []
    check_items = packing.make_items(manifests["train-agentic-000"],
                                     shards.load_tokens(shard_dir, manifests["train-agentic-000"]))[:60]
    for policy in ("structure_preserving", "best_fit", "long_context"):
        for p in packing.pack(check_items, 256, pad_id, policy):
            viol.extend(f"{policy}: {v}" for v in packing.verify_pack(p, eos_id, pad_id))
    # attention isolation: a packed sample must not see another
    sample_pack = packing.pack(check_items, 256, pad_id, "structure_preserving")[0]
    am = packing.attention_mask(sample_pack.segment_ids)
    cross = 0
    for i in range(len(am)):
        for j in range(i + 1):
            if am[i, j] and sample_pack.segment_ids[i] != sample_pack.segment_ids[j]:
                cross += 1
    log(f"  mask invariants: {len(viol)} violations; cross-segment attention permitted "
        f"in {cross} position pairs")
    json.dump({"policy_comparison": pol_rows, "mask_violations": viol,
               "cross_segment_attention_pairs": cross},
              open(os.path.join(art, "reports", "packing.json"), "w"), indent=1)
    log.event("batches packed")

    E.add("Packing correctness", not viol and cross == 0,
          [os.path.join("reports", "packing.json")],
          "loss masks, position id restarts and segment isolation checked on every packed sequence",
          {"mask_violations": viol, "cross_segment_attention_pairs": cross,
           "policies_compared": len(pol_rows),
           "best_occupancy": max(r["occupancy"] for r in pol_rows),
           "worst_occupancy": min(r["occupancy"] for r in pol_rows),
           "policy_table": [{k: r[k] for k in ("data", "policy", "occupancy", "loss_coverage",
                                               "n_sequences", "boundary_crossings",
                                               "truncated_samples")} for r in pol_rows]})

    # -------------------------------------------------------------- 14 learning ledger
    log.phase("14", "learning ledger: what came back from each shard")
    opus_by_shard = {}
    for d in opus.decisions:
        for s in d["shard_ids"]:
            opus_by_shard.setdefault(s, []).append(d["opus_score"])
    opus_mean = {k: round(sum(v) / len(v), 5) for k, v in opus_by_shard.items()}

    def phase_of(step):
        f = step / max(1, a.steps)
        return "early" if f < 0.34 else ("mid" if f < 0.66 else ("late" if f < 0.97 else "anneal"))

    learn_path = os.path.join(art, "ledgers", "learning_ledger.json")
    payload = trace.dump(learn_path, tok=tok, opus_scores=opus_mean, phase_of=phase_of)
    learning.write_token_trace(os.path.join(art, "ledgers", "token_trace.jsonl"), trace.rows)
    for card in payload["shard_report_cards"]:
        log(f"    {card['shard_id']:<22} lane {card['capability_lane']:<10} "
            f"tokens {card['loss_bearing_tokens_seen']:>7}  loss {card['avg_token_loss']:.3f}  "
            f"delta {card['loss_delta_after_exposure']:+.3f}  "
            f"opus {card['opus_mean_score']}  {card['classification']}")
    log(f"  hardest tokens overall: " +
        ", ".join(f"{r['decoded']!r}@{r['mean_perplexity']:.0f}"
                  for r in payload["hardest_token_clusters"][:5]))
    log(f"  hardest tokens in the Indic lane: " +
        ", ".join(f"{r['decoded']!r}@{r['mean_perplexity']:.0f}"
                  for r in payload["hardest_token_clusters_indic"][:5]))
    log(f"  full token traces kept for {sorted(trace.trace_shards)}: {len(trace.rows)} rows")
    epochs = resume_stream.epochs
    passes = {l: e + 1 for l, e in epochs.items()}
    log(f"  passes completed over each lane: " +
        ", ".join(f"{l}={passes[l]}" for l in mixture.LANES))
    if max(passes.values()) == 1:
        log("  no lane was consumed twice at this scale, so the repeated-pass columns "
            "are empty by measurement rather than by omission")
    payload["passes_per_lane"] = passes
    payload["cursor_state"] = {"cursors": resume_stream.cursors, "epochs": epochs}
    with open(learn_path, "w") as f:
        json.dump(payload, f, indent=1, ensure_ascii=False)

    linked = sum(1 for c in payload["shard_report_cards"] if c["loss_bearing_tokens_seen"] > 0)
    E.add("Learning trace linked to source data", linked >= 6 and len(trace.rows) > 0,
          [os.path.join("ledgers", "learning_ledger.json"),
           os.path.join("ledgers", "token_trace.jsonl")],
          "per-token cross entropy attributed back to shard, document, lane and token id",
          {"shards_with_report_cards": linked,
           "token_trace_rows": len(trace.rows),
           "lane_summary": payload["lane_summary"],
           "example_report_card": payload["shard_report_cards"][0],
           "hardest_indic_tokens": payload["hardest_token_clusters_indic"][:6]})

    # -------------------------------------------------------------- 15 audit
    log.phase("15", "audit: which data trained a token interval")
    total_positions = sum(r["n_sequences"] * r["sequence_length"] for r in seg0 + seg1)
    lo, hi = int(total_positions * 0.40), int(total_positions * 0.55)
    audit_out = tr.audit_token_range(sorted(seg0 + seg1, key=lambda r: (r["global_step"], r["rank"])), lo, hi)
    log(f"  tokens {lo:,} to {hi:,}: steps {audit_out['global_steps']}, "
        f"{audit_out['n_packed_samples']} packed samples")
    log(f"  shards involved: {list(audit_out['shards_involved'])[:6]}")
    json.dump(audit_out, open(os.path.join(art, "reports", "audit.json"), "w"), indent=1)
    log.event("audit completed")

    # never-train check across the entire consumption ledger
    never = registry.never_train_docs()
    leaked = sorted({m["doc_id"] for r in seg0 + seg1 for m in r["members"]} & never)
    log(f"  never-train documents that reached a loss-bearing batch: {len(leaked)}")

    E.add("Validation and test data never trained", not leaked,
          [os.path.join("reports", "audit.json"),
           os.path.join("ledgers", "consumption.main.jsonl")],
          "every document id in every consumed batch checked against the never-train registry",
          {"never_train_documents": len(never), "leaked_documents": leaked,
           "batches_checked": len(seg0) + len(seg1),
           "audit_example": audit_out})

    # -------------------------------------------------------------- 16 throughput
    log.phase("16", "throughput and packing efficiency")
    wall = time.time() - wall0
    perf.mark("run_a_seconds", run_a_seconds)
    perf.mark("resume_latency_seconds", resume_latency)
    perf.mark("replay_latency_seconds", replay_latency)
    report = perf.dump(os.path.join(art, "performance.json"), opus_audit=audit, wall=wall)
    recon = perf_mod.reconstruct_check(report, seg0 + seg1)
    report["reconstruction_from_ledger"] = recon
    json.dump(report, open(os.path.join(art, "performance.json"), "w"), indent=1)
    log(f"  raw {report['raw_tokens_per_second']:,.0f} tok/s   "
        f"useful {report['useful_loss_bearing_tokens_per_second']:,.0f} tok/s   "
        f"accepted {report['accepted_tokens_per_second']:,.0f} tok/s")
    log(f"  packing occupancy {report['packing_occupancy']:.4f}   loss coverage "
        f"{report['loss_coverage_of_positions']:.4f}   loader wait "
        f"{report['loader_wait_fraction']:.4f}")
    log(f"  reconstruction from the ledger: raw {recon['ledger_raw_token_positions']:,} "
        f"against {recon['report_raw_token_positions']:,}, "
        f"{'matches' if recon['ok'] else 'DOES NOT MATCH'}")
    log.event("performance measured")

    E.add("Throughput reconstructable from the ledger", recon["ok"],
          ["performance.json", os.path.join("ledgers", "consumption.main.jsonl")],
          "headline token counts recounted from the consumption ledger and compared to the report",
          {**recon,
           "raw_tokens_per_second": report["raw_tokens_per_second"],
           "useful_loss_bearing_tokens_per_second": report["useful_loss_bearing_tokens_per_second"],
           "accepted_tokens_per_second": report["accepted_tokens_per_second"],
           "packing_occupancy": report["packing_occupancy"]})

    E.add("End to end execution", True,
          ["run.log"],
          "all phases ran in one command without manual intervention",
          {"phases": 18, "wall_seconds": round(wall, 2),
           "steps_trained": resume_stream.step,
           "checkpoints": len(trainer.checkpoints) + len(resume_trainer.checkpoints),
           "ledger_records": len(all_records)})

    # -------------------------------------------------------------- invariant tests
    log.phase("17", "invariant tests")
    import subprocess
    t = time.time()
    proc = subprocess.run([sys.executable, "-m", "unittest", "discover", "-s", "tests"],
                          cwd=HERE, capture_output=True, text=True)
    tail = (proc.stderr or proc.stdout).strip().splitlines()
    ran = next((l for l in tail if l.startswith("Ran ")), "")
    verdict = tail[-1] if tail else ""
    log(f"  {ran} in {time.time() - t:.1f}s -> {verdict}")
    with open(os.path.join(art, "reports", "tests.txt"), "w") as f:
        f.write(proc.stdout + "\n" + proc.stderr)
    n_tests = int(ran.split()[1]) if ran.startswith("Ran ") else 0

    E.add("Invariant tests", proc.returncode == 0 and n_tests > 0,
          [os.path.join("reports", "tests.txt")],
          "the unit test suite was executed by this run, not quoted from a previous one",
          {"tests_run": n_tests, "exit_code": proc.returncode, "verdict": verdict,
           "command": "python -m unittest discover -s tests"})

    # -------------------------------------------------------------- checkpoint index
    all_ckpts = (trainer.checkpoints + resume_trainer.checkpoints +
                 fork_trainer.checkpoints)
    needed = {last_ckpt["checkpoint_id"], eck["checkpoint_id"]}
    if trainer.checkpoints:
        needed.add(trainer.checkpoints[0]["checkpoint_id"])
    if resume_trainer.checkpoints:
        needed.add(resume_trainer.checkpoints[-1]["checkpoint_id"])
    for c in all_ckpts:
        if c["checkpoint_id"] not in needed and c["retained"] and os.path.exists(c["path"]):
            os.remove(c["path"])
            c["retained"] = False
    index = {
        "note": "Checkpoint weights are regenerated by run_demo.py and are not "
                "committed.  Every checkpoint ever written is listed here with the "
                "ledger offset it is bound to and a digest of its weights, so a "
                "checkpoint that is no longer on disk is still identified.",
        "retained_on_disk": sorted(c["checkpoint_id"] for c in all_ckpts if c["retained"]),
        "checkpoints": [{k: v for k, v in c.items() if k != "path"} for c in all_ckpts],
    }
    with open(os.path.join(art, "checkpoints", "index.json"), "w") as f:
        json.dump(index, f, indent=1)
    ckpt_bytes = sum(os.path.getsize(c["path"]) for c in all_ckpts
                     if c["retained"] and os.path.exists(c["path"]))
    log(f"  checkpoints: {len(all_ckpts)} written, {len(index['retained_on_disk'])} kept "
        f"on disk ({ckpt_bytes / 1e6:.0f} MB), all indexed with weight digests")

    E.add("Checkpoints bound to ledger offsets",
          all(c["ledger_offset"] is not None for c in all_ckpts) and len(all_ckpts) > 2,
          [os.path.join("checkpoints", "index.json")],
          "every checkpoint records the ledger offset, token count and weight digest it was written at",
          {"n_checkpoints": len(all_ckpts),
           "retained_on_disk": index["retained_on_disk"],
           "resume_checkpoint": last_ckpt["checkpoint_id"],
           "replay_checkpoint": eck["checkpoint_id"],
           "examples": index["checkpoints"][:4]})

    # -------------------------------------------------------------- evidence bundle
    log.phase("18", "evidence bundle")
    summary = {
        "run_id": RUN_ID, "parameters": parameter_count(model),
        "vocab_size": tok.get_vocab_size(), "tokenizer_hash": tokenizer_hash,
        "steps": resume_stream.step, "token_positions": total_positions,
    }
    payload = E.write_json(os.path.join(art, "evidence.json"), extra={"run": summary})
    E.write_md(os.path.join(art, "evidence.md"), summary)
    for c in E.checks:
        log(f"  [{c['result']}] {c['requirement']}")
    log("")
    log(f"{payload['n_checks'] - payload['n_failed']} of {payload['n_checks']} checks passed "
        f"in {wall:.1f}s")
    log.event("[PASS] evidence_bundle_generated" if payload["all_passed"]
              else "[FAIL] evidence bundle contains failures")
    log.close()
    return 0 if payload["all_passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
